# Generated by Django 5.2.8 on 2025-11-28 09:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("other_names", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Student email address for communication",
                        max_length=255,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Student contact number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone must be: +233XXXXXXXXX or 0XXXXXXXXX",
                                regex="^(\\+233|0)[2-5][0-9]{8}$",
                            )
                        ],
                    ),
                ),
                ("residential_address", models.TextField(blank=True)),
                (
                    "student_id",
                    models.CharField(
                        help_text="Unique student identification number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "admission_date",
                    models.DateField(
                        help_text="Date student was admitted to the school"
                    ),
                ),
                (
                    "current_grade",
                    models.CharField(
                        help_text="Current grade/class (e.g., Grade 1, JHS 2, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        help_text="Full name of parent/guardian", max_length=200
                    ),
                ),
                (
                    "guardian_relationship",
                    models.CharField(
                        default="Parent",
                        help_text="Relationship to student (Parent, Guardian, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        help_text="Guardian primary contact number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone must be: +233XXXXXXXXX or 0XXXXXXXXX",
                                regex="^(\\+233|0)[2-5][0-9]{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "guardian_email",
                    models.EmailField(
                        blank=True, help_text="Guardian email address", max_length=255
                    ),
                ),
                (
                    "guardian_address",
                    models.TextField(
                        blank=True, help_text="Guardian residential address"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, help_text="Emergency contact person", max_length=200
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone must be: +233XXXXXXXXX or 0XXXXXXXXX",
                                regex="^(\\+233|0)[2-5][0-9]{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Any medical conditions, allergies, or special needs",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Student photograph",
                        null=True,
                        upload_to="students/photos/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the student is currently enrolled",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional user account for system access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "student",
                "verbose_name_plural": "students",
                "ordering": ["current_grade", "last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["student_id"], name="students_st_student_e7126a_idx"
                    ),
                    models.Index(
                        fields=["current_grade", "is_active"],
                        name="students_st_current_ca8421_idx",
                    ),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="students_st_last_na_3e473b_idx",
                    ),
                ],
            },
        ),
    ]
