# Generated by Django 5.2.8 on 2025-11-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Programme name (e.g., General Science, Business, Visual Arts)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Programme code (e.g., SCI, BUS, VART)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Programme description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this programme is currently offered",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "programme",
                "verbose_name_plural": "programmes",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="student",
            name="current_grade",
            field=models.CharField(
                choices=[
                    ("Nursery", "Nursery"),
                    ("KG 1", "KG 1"),
                    ("KG 2", "KG 2"),
                    ("Primary 1", "Primary 1"),
                    ("Primary 2", "Primary 2"),
                    ("Primary 3", "Primary 3"),
                    ("Primary 4", "Primary 4"),
                    ("Primary 5", "Primary 5"),
                    ("Primary 6", "Primary 6"),
                    ("JHS 1", "JHS 1"),
                    ("JHS 2", "JHS 2"),
                    ("JHS 3", "JHS 3"),
                    ("SHS 1", "SHS 1"),
                    ("SHS 2", "SHS 2"),
                    ("SHS 3", "SHS 3"),
                ],
                help_text="Current grade/class",
                max_length=50,
            ),
        ),
    ]
