# Generated by Django 5.2.8 on 2025-11-28 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("teachers", "0002_teacher_email_alter_teacher_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subject name (e.g., Mathematics, English)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Subject code (e.g., MATH101, ENG101)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Subject description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this subject is currently offered",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "subject",
                "verbose_name_plural": "subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Class name (e.g., Grade 1A, JHS 2B, Form 3)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        help_text="Grade/level (e.g., Grade 1, JHS 2, SHS 1)",
                        max_length=50,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Section/stream (e.g., A, B, C, Science, Arts)",
                        max_length=10,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="Maximum number of students",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Academic year (e.g., 2024/2025)", max_length=20
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, help_text="Classroom number/location", max_length=50
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this class is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Class teacher/Form master",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homeroom_classes",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "class",
                "verbose_name_plural": "classes",
                "ordering": ["grade_level", "section", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        help_text="Date student was enrolled in this class"
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Date student completed/left this class",
                        null=True,
                    ),
                ),
                (
                    "roll_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Student roll number in this class",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this enrollment is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this enrollment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="classes.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "student enrollment",
                "verbose_name_plural": "student enrollments",
                "ordering": ["-enrollment_date", "roll_number"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periods_per_week",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of periods per week",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this subject is currently being taught",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="classes.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher assigned to teach this subject in this class",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_assignments",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_assignments",
                        to="classes.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "class subject",
                "verbose_name_plural": "class subjects",
                "ordering": ["class_obj", "subject"],
            },
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["grade_level", "is_active"],
                name="classes_cla_grade_l_b8332b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["academic_year", "is_active"],
                name="classes_cla_academi_727293_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["student", "is_active"], name="classes_stu_student_3c780f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["class_obj", "is_active"], name="classes_stu_class_o_c7fe00_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_obj", "subject")},
        ),
    ]
