# Generated by Django 5.2.8 on 2025-11-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("Nursery", "Nursery"),
                    ("KG 1", "KG 1"),
                    ("KG 2", "KG 2"),
                    ("Primary 1", "Primary 1"),
                    ("Primary 2", "Primary 2"),
                    ("Primary 3", "Primary 3"),
                    ("Primary 4", "Primary 4"),
                    ("Primary 5", "Primary 5"),
                    ("Primary 6", "Primary 6"),
                    ("JHS 1", "JHS 1"),
                    ("JHS 2", "JHS 2"),
                    ("JHS 3", "JHS 3"),
                    ("SHS 1", "SHS 1"),
                    ("SHS 2", "SHS 2"),
                    ("SHS 3", "SHS 3"),
                ],
                help_text="Select grade/level",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(
                editable=False,
                help_text="Auto-generated from grade level and section",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("grade_level", "section", "academic_year")},
        ),
    ]
