# Generated by Django 5.2.8 on 2025-11-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_class_grade_level_alter_class_name_and_more"),
        ("students", "0002_programme_alter_student_current_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic programme (for SHS classes only - e.g., Science, Business, Visual Arts)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="students.programme",
            ),
        ),
    ]
