# Generated by Django 5.2.8 on 2025-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_class_programme"),
        ("students", "0002_programme_alter_student_current_grade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentenrollment",
            options={
                "ordering": ["-academic_year", "-enrollment_date", "roll_number"],
                "verbose_name": "student enrollment",
                "verbose_name_plural": "student enrollments",
            },
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="academic_year",
            field=models.CharField(
                db_index=True,
                default="2024/2025",
                help_text="Academic year for this enrollment (e.g., 2024/2025)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="final_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("promoted", "Promoted to Next Grade"),
                    ("repeated", "Repeated Grade"),
                    ("graduated", "Graduated"),
                    ("transferred", "Transferred"),
                    ("withdrawn", "Withdrawn"),
                    ("pending", "Pending (Year Not Complete)"),
                ],
                default="pending",
                help_text="Final outcome of this enrollment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("enrolled", "Currently Enrolled"),
                    ("completed", "Completed"),
                    ("withdrawn", "Withdrawn"),
                    ("transferred", "Transferred Out"),
                ],
                default="enrolled",
                help_text="Current status of this enrollment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this is the current enrollment (current academic year only)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["academic_year", "is_active"],
                name="classes_stu_academi_72dde8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["student", "academic_year"],
                name="classes_stu_student_e242a0_idx",
            ),
        ),
    ]
