# Generated by Django 5.2.8 on 2025-11-27 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(
                default=django.utils.timezone.now,
                help_text="Teacher email address for communication",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional user account for system access",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
