# Generated by Django 5.2.8 on 2025-11-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        default="SmartSIS",
                        help_text="Short name displayed in navbar",
                        max_length=20,
                    ),
                ),
                (
                    "motto",
                    models.CharField(
                        blank=True, help_text="School motto or tagline", max_length=100
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="School logo",
                        null=True,
                        upload_to="school_logos/",
                    ),
                ),
                (
                    "theme_name",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("cupcake", "Cupcake"),
                            ("emerald", "Emerald"),
                            ("corporate", "Corporate"),
                            ("forest", "Forest"),
                            ("luxury", "Luxury"),
                        ],
                        default="light",
                        help_text="DaisyUI theme",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Settings",
                "verbose_name_plural": "School Settings",
            },
        ),
    ]
