# Generated by Django 5.2.8 on 2025-11-28 21:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0004_alter_studentenrollment_options_and_more"),
        ("students", "0002_programme_alter_student_current_grade"),
        ("teachers", "0002_teacher_email_alter_teacher_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., CT, ASG, EXAM)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_exam",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this if it is an end-of-term exam",
                    ),
                ),
                (
                    "default_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default weight percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "default_max_score",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Default maximum score for this assessment type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_exam", "name"],
            },
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        help_text="Grade symbol (e.g., A1, B2, C3, etc.)",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "min_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        help_text="Grade interpretation (e.g., Excellent, Very Good)",
                        max_length=50,
                    ),
                ),
                (
                    "grade_point",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grade point for GPA calculation",
                        max_digits=3,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="Additional remarks for this grade range",
                        max_length=100,
                    ),
                ),
                (
                    "is_passing",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if this grade is a passing grade",
                    ),
                ),
            ],
            options={
                "ordering": ["-min_score"],
            },
        ),
        migrations.CreateModel(
            name="GradingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Academic year (e.g., 2024/2025)", max_length=20
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("term_1", "First Term"),
                            ("term_2", "Second Term"),
                            ("term_3", "Third Term"),
                        ],
                        default="term_1",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "grade_entry_deadline",
                    models.DateField(
                        help_text="Last date for teachers to enter grades"
                    ),
                ),
                (
                    "report_generation_date",
                    models.DateField(help_text="Date when report cards are generated"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Only one grading period can be current at a time",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-academic_year", "-term"],
                "indexes": [
                    models.Index(
                        fields=["academic_year", "term"],
                        name="grading_gra_academi_a2bda6_idx",
                    ),
                    models.Index(
                        fields=["is_current"], name="grading_gra_is_curr_dc8a8f_idx"
                    ),
                ],
                "unique_together": {("academic_year", "term")},
            },
        ),
        migrations.CreateModel(
            name="SubjectAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Specific name for this assessment (e.g., "Mid-Term Math Test")',
                        max_length=200,
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum possible score",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight in final grade calculation (%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("date_conducted", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Students can view their scores when published",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="grading.assessmenttype",
                    ),
                ),
                (
                    "class_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="classes.classsubject",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assessments",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="grading.gradingperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_conducted"],
            },
        ),
        migrations.CreateModel(
            name="StudentGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score obtained (e.g., 85.5)",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_excused",
                    models.BooleanField(
                        default=False,
                        help_text="Student was absent/excused from this assessment",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Teacher comments on this specific assessment",
                    ),
                ),
                ("graded_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        help_text="Links grade to specific enrollment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="classes.studentenrollment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_assessments",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.student",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="grading.subjectassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["student__last_name", "student__first_name"],
            },
        ),
        migrations.CreateModel(
            name="TermGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "continuous_assessment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sum of continuous assessment (non-exam) scores",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Exam score",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final weighted total score",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Letter grade (A1, B2, etc.)",
                        max_length=2,
                    ),
                ),
                (
                    "grade_point",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "class_position",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Position in class for this subject",
                        null=True,
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(blank=True, help_text="Subject teacher comment"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_grades",
                        to="classes.classsubject",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_grades",
                        to="classes.studentenrollment",
                    ),
                ),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_grades",
                        to="grading.gradingperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_score"],
            },
        ),
        migrations.CreateModel(
            name="ConductGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conduct_area",
                    models.CharField(
                        choices=[
                            ("attendance", "Attendance"),
                            ("punctuality", "Punctuality"),
                            ("neatness", "Neatness"),
                            ("politeness", "Politeness"),
                            ("honesty", "Honesty"),
                            ("leadership", "Leadership"),
                            ("relationship", "Relationship with Others"),
                            ("attitude", "Attitude to Work"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("5", "Excellent"),
                            ("4", "Very Good"),
                            ("3", "Good"),
                            ("2", "Satisfactory"),
                            ("1", "Needs Improvement"),
                        ],
                        max_length=1,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conduct_grades",
                        to="classes.studentenrollment",
                    ),
                ),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conduct_grades",
                        to="grading.gradingperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["conduct_area"],
                "unique_together": {("enrollment", "grading_period", "conduct_area")},
            },
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sum of all subject scores",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grade Point Average",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "class_position",
                    models.PositiveIntegerField(
                        blank=True, help_text="Overall position in class", null=True
                    ),
                ),
                (
                    "total_students",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total students in class", null=True
                    ),
                ),
                ("days_present", models.PositiveIntegerField(default=0)),
                ("days_absent", models.PositiveIntegerField(default=0)),
                ("days_school_opened", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("class_teacher_comment", models.TextField(blank=True)),
                ("head_teacher_comment", models.TextField(blank=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Report card visible to students/parents",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="classes.studentenrollment",
                    ),
                ),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="grading.gradingperiod",
                    ),
                ),
                (
                    "promoted_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Class student is promoted to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_from_reports",
                        to="classes.class",
                    ),
                ),
            ],
            options={
                "ordering": ["-grading_period", "-average_score"],
                "indexes": [
                    models.Index(
                        fields=["grading_period", "is_published"],
                        name="grading_rep_grading_889115_idx",
                    ),
                    models.Index(
                        fields=["enrollment", "grading_period"],
                        name="grading_rep_enrollm_7d09d6_idx",
                    ),
                ],
                "unique_together": {("enrollment", "grading_period")},
            },
        ),
        migrations.AddIndex(
            model_name="subjectassessment",
            index=models.Index(
                fields=["class_subject", "grading_period"],
                name="grading_sub_class_s_fce0eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectassessment",
            index=models.Index(
                fields=["grading_period", "is_published"],
                name="grading_sub_grading_098400_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentgrade",
            index=models.Index(
                fields=["assessment", "student"], name="grading_stu_assessm_52e1b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentgrade",
            index=models.Index(
                fields=["student", "enrollment"], name="grading_stu_student_7cb935_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentgrade",
            unique_together={("assessment", "student")},
        ),
        migrations.AddIndex(
            model_name="termgrade",
            index=models.Index(
                fields=["grading_period", "class_subject"],
                name="grading_ter_grading_0c1421_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="termgrade",
            index=models.Index(
                fields=["enrollment", "grading_period"],
                name="grading_ter_enrollm_a74e50_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="termgrade",
            unique_together={("enrollment", "class_subject", "grading_period")},
        ),
    ]
