# Generated by Django 5.0.8 on 2024-09-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_signuptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.UUIDField(default='FDHDQURA9C', editable=False, unique=True),
        ),
    ]
