# Generated by Django 5.0.8 on 2024-09-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_signuptoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.UUIDField(default='UHSZTVMVS6', editable=False, unique=True),
        ),
    ]
