# Generated by Django 5.0.8 on 2024-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_signuptoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, default='', max_length=50)),
                ('street_name', models.CharField(blank=True, default='', max_length=255)),
                ('landmark', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('gps_address', models.CharField(blank=True, default='', max_length=15)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('telephone', models.CharField(blank=True, default='', max_length=32)),
                ('mobile_no', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default='2O46EYPK4P', editable=False, unique=True),
        ),
    ]
