# Generated by Django 5.0.8 on 2024-09-07 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_address_alter_signuptoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.signuptoken'),
        ),
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default='O7BAWPIG7I', editable=False, unique=True),
        ),
    ]
