# Generated by Django 5.0.8 on 2024-09-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_token_alter_signuptoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default='0TV2AVXGMB', editable=False, unique=True),
        ),
    ]
