# Generated by Django 5.0.8 on 2024-09-14 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_signuptoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default='CL2B2J4GXX', editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('other_names', models.CharField(blank=True, default='', max_length=32)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(blank=True, choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('traditional african religion', 'Traditional African Religion')], default='', max_length=32)),
                ('religious_denomination', models.CharField(blank=True, default='', max_length=32)),
                ('nationality', models.CharField(max_length=128)),
                ('national_id', models.CharField(blank=True, default='', max_length=32)),
                ('social_security_no', models.CharField(blank=True, default='', max_length=32)),
                ('health_insurance_no', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Dr.', 'Dr.'), ('Hon', 'Hon'), ('Hon.', 'Hon.'), ('Lord', 'Lord'), ('Md.', 'Md.'), ('Ms', 'Ms'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Prof', 'Prof'), ('Prof', 'Prof'), ('Rev', 'Rev'), ('Rev.', 'Rev.'), ('Sir', 'Sir')], max_length=32)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_address', to='core.address')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='core.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notional_date', models.DateField(blank=True, null=True)),
                ('substantive_date', models.DateField()),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.teacher')),
            ],
        ),
    ]
