# Generated by Django 5.0.8 on 2024-09-20 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_signuptoken_token_teacher_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default='AIKVMTCA3G', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_address', to='core.address'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='other_names',
            field=models.CharField(max_length=32),
        ),
    ]
