# Generated by Django 5.0.8 on 2024-09-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_teacher_is_active_remove_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default='UEFN6HZXJP', editable=False, unique=True),
        ),
    ]
