# Generated by Django 5.0.8 on 2024-09-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_signuptoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptoken',
            name='token',
            field=models.CharField(default='LJINBFXWRB', editable=False, unique=True),
        ),
    ]
