# Generated by Django 5.2.8 on 2025-11-28 20:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0004_alter_studentenrollment_options_and_more"),
        ("students", "0002_programme_alter_student_current_grade"),
        ("teachers", "0002_teacher_email_alter_teacher_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Attendance"),
                            ("subject", "Subject/Period Attendance"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "period_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Period number for subject attendance (1-8)",
                        null=True,
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="Once finalized, attendance cannot be changed",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="classes.class",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teachers.teacher",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for subject-specific attendance",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.classsubject",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused Absence"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "time_in",
                    models.TimeField(
                        blank=True,
                        help_text="Time of arrival for late students",
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        help_text="The enrollment this attendance is tied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="classes.studentenrollment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="attendance.attendancesession",
                    ),
                ),
            ],
            options={
                "ordering": ["student__last_name", "student__first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["class_obj", "date"], name="attendance__class_o_d69413_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["date", "session_type"], name="attendance__date_bb584c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesession",
            unique_together={
                ("class_obj", "date", "session_type", "subject", "period_number")
            },
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["session", "status"], name="attendance__session_8dae34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["student", "status"], name="attendance__student_fb4d40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["enrollment", "status"], name="attendance__enrollm_308d93_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("session", "student")},
        ),
    ]
